general:
  logging: debug
  logging_to_disk: False

run:
  project: southern_africa
  experiment: species
  identifier: timestamp

paths:
  root: '/host/data_hdd/'
  experiments: 'experiments/'
  models: 'models/'


models:
  resnet18:
    batch_size: 128

projects:
  southern_africa:
    experiment_id: 'ts'
    image_processing:
      image_save_side_max: 500
      output_height: 224
      output_width: 224
      resize_side_min: 224
      resize_side_max: 500
    paths:
      master_tfr: 'master.tfrecord'
      #inventory: 'D:\Studium_GD\Zooniverse\CamCatProject\data\inventory_list.csv'
      inventory: 'inventory_list.csv'
    training_splits:
      train: 0.9
      validation: 0.05
      test: 0.05
    experiments:
      empty_vehicle_species:
        model: resnet18
        labels_project: panthera
        labels_version: empty
        label_types_to_model:
          - 'primary'
        balanced_sampling_min: False
        balanced_sampling_label_type: 'primary'
      species:
        model: resnet18
        labels_project: panthera
        labels_version: species
        label_types_to_model:
          - 'primary'
        balanced_sampling_min: False
        balanced_sampling_label_type: 'primary'
