###########################################
# MODELS ########################
###########################################

models:
  # Model name
  ResNet18:
    image_processing:
      # image output size of pre-processing (input to training)
      output_height: 224
      output_width: 224
  ResNet34:
    image_processing:
      output_height: 224
      output_width: 224
  ResNet50:
    image_processing:
      output_height: 224
      output_width: 224
  ResNet101:
    image_processing:
      output_height: 224
      output_width: 224
  ResNet152:
    image_processing:
      output_height: 224
      output_width: 224
  InceptionResNetV2:
    image_processing:
      output_height: 299
      output_width: 299
  Xception:
    image_processing:
      output_height: 299
      output_width: 299
  small_cnn:
    image_processing:
      output_height: 50
      output_width: 50


###########################################
# Data Augmentation - Default Parameters
###########################################

image_processing:
  preserve_aspect_ratio: False
  crop_factor: 0.1
  zoom_factor: 0.1
  rotate_by_angle: 5
  color_augmentation: full_randomized
  randomly_flip_horizontally: True
  image_choice_for_sets: random
