###########################################
# AVAILABLE MODELS ########################
###########################################

models:
  # Model name
  ResNet18:
    image_processing:
      # image output size of pre-processing (input to training)
      output_height: 224
      output_width: 224
      # resizing options for data augmentation
      resize_side_min: 224
      resize_side_max: 246
      # whether to use color data augmentation (randomly adjust colors)
      color_manipulations: True
  ResNet34:
    image_processing:
      output_height: 224
      output_width: 224
      resize_side_min: 224
      resize_side_max: 246
      color_manipulations: True
  ResNet50:
    image_processing:
      output_height: 224
      output_width: 224
      resize_side_min: 224
      resize_side_max: 246
      color_manipulations: True
  ResNet101:
    image_processing:
      output_height: 224
      output_width: 224
      resize_side_min: 224
      resize_side_max: 246
      color_manipulations: True
  ResNet152:
    image_processing:
      output_height: 224
      output_width: 224
      resize_side_min: 224
      resize_side_max: 246
      color_manipulations: True
  InceptionResNetV2:
    image_processing:
      output_height: 299
      output_width: 299
      resize_side_min: 299
      resize_side_max: 329
      color_manipulations: True
  cats_vs_dogs:
    image_processing:
      output_height: 150
      output_width: 150
      resize_side_min: 150
      resize_side_max: 165
      color_manipulations: True
